const burger = [
    {id:1,
    img:'/assets/images/Burger-cheddar-panceta.jpg',
    name:'Simple',
    price:4500,
    description:'Burger simple con cheddar y panceta',
    },
    {id:2,
    img:'/assets/images/Burger2-cheddar-panceta.jpg',
    name:'Doble',
    price:5000,
    description:'Burger doble con cheddar y panceta',
    },
    {id:3,
    img:'/assets/images/Burger3-cheddar-panceta.jpg',
    name:'Triple',
    price:5500,
    description:'Burger triple con cheddar y panceta',
    },
    {id:4,
    img:'/assets/images/burger-mexicana.jpg',
    name:'Mexicana',
    price:5000,
    description:'Burger simple picante',
    },
    {id:5,
    img:'/assets/images/burger-provole-pimientos.jpg',
    name:'Bodegon',
    price:6000,
    description:'Burger simple con queso provolone y morrones asados',
    },
    {id:6,
    img:'/assets/images/burger-chimi.jpg',
    name:'Argenta',
    price:5250,
    description:'Burger simple con queso tybo y chimichurri',
    },
    {id:7,
    img:'/assets/images/burger-pollo-crispy2.jpg',
    name:'MeatCrispy',
    price:6500,
    description:'Burger con doble medallon de pollo crispy',
    },
    {id:8,
    img:'/assets/images/burger-vegana.jpg',
    name:'VeganCraft',
    price:5300,
    description:'Burger con medallon vegano con salsa de la casa y palta',
    }
]